### ISSUE TITLE
GitHub Login: 500 on redirect after authorization

### ISSUE THREAD

**Issue by Lootwig** [sveltejs/sites#379]
On local repo clone + reproduction (navigate to /repl route + clicking "Log in to save", then authorize application on popup), server side error stacktrace is:

```
GET /auth/callback Error: Could not find the public.signin(user_github_avatar_url, user_github_id, user_github_login, user_github_name) function or the public.signin function with a single unnamed json or jsonb parameter in the schema cache
    at Module.create (/src/lib/db/session.js:27:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GET (/Users/davidschneider/projects/contribution/sites/sites/svelte.dev/src/routes/auth/callback/+server.js:46:34)
    at async render_endpoint (file:///Users/davidschneider/projects/contribution/sites/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.456_svelte@3.49.0+vite@3.1.0/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:37:20)
    at async resolve (file:///Users/davidschneider/projects/contribution/sites/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.456_svelte@3.49.0+vite@3.1.0/node_modules/@sveltejs/kit/src/runtime/server/index.js:244:18)
    at async respond (file:///Users/davidschneider/projects/contribution/sites/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.456_svelte@3.49.0+vite@3.1.0/node_modules/@sveltejs/kit/src/runtime/server/index.js:196:20)
    at async file:///Users/davidschneider/projects/contribution/sites/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.456_svelte@3.49.0+vite@3.1.0/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:376:22
```

**Comment by benmccann** [comment]
I believe this works in production, so it's some issue with how you're setup to test locally

**Comment by Lootwig** [comment]
Yes true, can't reproduce in production either (which I could back when I faced this during summit, just noticed I mistyped as "reproduction" in original message...)
