### ISSUE TITLE
RSS feed request returns 500 internal error

### ISSUE THREAD

**Issue by simevidas** [sveltejs/sites#415]
https://svelte.dev/blog/rss.xml

<img width="588" alt="Screenshot 2022-12-14 at 23 09 00" src="https://user-images.githubusercontent.com/716405/207726150-456ca5ef-eece-4413-bc5b-d1f543285072.png">

**Comment by benmccann** [comment]
```
[GET] /blog/rss.xml
14:48:47:90
2022-12-14T22:48:47.923Z	30440555-7e4a-4013-a430-223fc85ecc3c	ERROR	Error: ENOENT: no such file or directory, scandir 'content/blog'
    at Object.readdirSync (node:fs:1405:3)
    at get_index (file:///var/task/sites/svelte.dev/.svelte-kit/output/server/chunks/index4.js:142:13)
    at GET (file:///var/task/sites/svelte.dev/.svelte-kit/output/server/entries/endpoints/blog/rss.xml/_server.js:45:17)
    at render_endpoint (file:///var/task/sites/svelte.dev/.svelte-kit/output/server/index.js:305:28)
    at resolve (file:///var/task/sites/svelte.dev/.svelte-kit/output/server/index.js:2310:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond (file:///var/task/sites/svelte.dev/.svelte-kit/output/server/index.js:2206:22)
    at async Server.default (file:///var/task/sites/svelte.dev/.svelte-kit/vercel-tmp/index.js:31:3)
```

**Comment by geoffrich** [comment]
Rich prerendered all the blog posts in #413 - my guess is the RSS feed needs to be prerendered as well.
